FROM dovecot/dovecot

# Install coreutils or the specific utility you need
# The installation method depends on the base image's package manager
# For example, if the base is Alpine:
#RUN apk update && apk add coreutils
# For Debian/Ubuntu base:
# RUN apt-get update && apt-get install -y coreutils
# For CentOS/Fedora base:
# RUN yum install -y coreutils

# If no package manager is available, you might need to compile from source or copy the binaries

