

services:
  auth:
    container_name: auth
    build:
      context: auth
      dockerfile: Dockerfile
    env_file:
      - path: ./auth/.env.dev
  ftp:
    container_name: ftp
    build:
      context: ftp
      dockerfile: Dockerfile
    networks:
      abc:
        ipv4_address: 192.168.0.21
    ports:
      - "20:20"
      - "21:21"
      - "40000:40000"
      - "50000:50000"
networks:
  abc:
    ipam:
      config:
        - subnet: 192.168.0.0/24
    attachable: true



