services:
  dns:
    image: nsd
    container_name: dns
    build:
      context: dns
      dockerfile: Dockerfile
    networks:
      local-docker-network:
        ipv4_address: 192.168.50.2

  mail:
    image: mail 
    container_name: mail
    build:
      context: ./mail
      dockerfile: Dockerfile
    ports:
      - "25:25"     # SMTP
      - "143:143"   # IMAP
      - "587:587"   # SMTP Submission
      - "993:993"   # IMAPS
    environment:
      HOSTNAME: mail.test.local
    networks:
      local-docker-network:
        ipv4_address: 192.168.50.3

networks:
  local-docker-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.50.0/24

