services:
  dns:
    image: nsd
    container_name: dns
    build:
      context: ./dns
      dockerfile: Dockerfile
    networks:
      local-docker-network:
        ipv4_address: 192.168.50.2

  mail:
    image: mail 
    container_name: mail
    build:
      context: ./mail
      dockerfile: Dockerfile
    ports:
      - "25:25"     
      - "143:143"
      - "587:587"
      - "993:993"
    hostname: mail.example.com
    environment:
      HOSTNAME: mail.example.com
    networks:
      local-docker-network:
        ipv4_address: 192.168.50.3
    dns: 
      - 192.168.50.2
      - 8.8.8.8

  imap:
    image: imap 
    container_name: imap
    networks:
      local-docker-network:
        ipv4_address: 192.168.50.101
    ports:
      - 31143:31143
      - 31993:31993
      - 31587:31587
      - 31024:31024
      - 34190:34190
      - 8080:8080
      - 9090:9090
    dns:
      - 192.168.50.2
      - 8.8.8.8

  ws1:
    image: ws1
    container_name: ws1
    command: tail -f /dev/null
    networks:
      local-docker-network:
        ipv4_address: 192.168.50.100
    ports:
      - "7000:7000"
      - "8000:8000"
    dns: 8.8.8.8 

networks:
  local-docker-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.50.0/24

